// qwik/src/routes/movie/[id]/index.tsx
import { component$, useSignal, useStylesScoped$, useTask$ } from '@builder.io/qwik';
import { getMovieDetails, MovieDto, PosterPath } from '~/services/MoviesApi';
import { useLocation } from '@builder.io/qwik-city';
import styles from './index.scss?inline';

export default component$(() => {
  useStylesScoped$(styles);

  const location = useLocation();
  const data = useSignal(null as MovieDto | null);

  useTask$(async () => {
    const response = await getMovieDetails(location.params.id);
    data.value = await response.json();
  });

  return <article>
      <img src={`${PosterPath}${data.value?.poster_path}`} alt={data.value?.original_title} />

      <h1>{data.value?.original_title}</h1>

      <p>{data.value?.overview}</p>
    </article>
});

// svelte/src/routes/movie/[id]/+page.svelte
<script lang="ts">
  import { PosterPath } from '../../../services/MoviesApi';
  import type { PageData } from './$types';
  export let data: PageData;

  console.log(data);
</script>

<article>
  <img src={`${PosterPath}${data.poster_path}`} alt={data.original_title} />

  <h1>{data.original_title}</h1>

  <p>{data.overview}</p>
</article>

<style lang="scss" scoped>
  article {
    text-align: center;
    img {
      width: 100%;
      border-radius: 12px;
    }
  }
</style>
